### ISSUE TITLE
Fix FCFS-IAD3-LAB06 provider network VLAN ranges

### ISSUE THREAD

**Issue by jpmontez** [rcbops/jenkins-oa#44]
The provider network VLAN range is currently:

```
        - name: provider
          bridge: br-vlan
          container_interface: eth11
          container_type: veth
          type: vlan
          range: 235
          net_name: vlan
          group_binds:
            - neutron_linuxbridge_agent
```

Neutron requires a range to consistent of two values. Otherwise, you get the following traceback:

```
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan [-] Failed to parse network_vlan_ranges. Service terminated!
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan Traceback (most recent call last):
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan   File "/openstack/venvs/neutron-12.2.8/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 92, in _parse_network_vlan_ranges
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan     cfg.CONF.ml2_type_vlan.network_vlan_ranges)
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan   File "/openstack/venvs/neutron-12.2.8/lib/python2.7/site-packages/neutron/plugins/common/utils.py", line 95, in parse_network_vlan_ranges
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan     network, vlan_range = parse_network_vlan_range(entry)
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan   File "/openstack/venvs/neutron-12.2.8/lib/python2.7/site-packages/neutron/plugins/common/utils.py", line 82, in parse_network_vlan_range
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan     raise n_exc.NetworkVlanRangeError(vlan_range=entry, error=ex)
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan NetworkVlanRangeError: Invalid network VLAN range: 'vlan:235' - 'need more than 2 values to unpack'
2016-11-28 14:16:22.655 31384 ERROR neutron.plugins.ml2.drivers.type_vlan 
```

**Comment by jpmontez** [comment]
Committed a patch for this change. Currently testing it within the lab environment.
